[package]
name = "genmask-rs"
version = "0.1.0"
authors = ["Joel Stanley <joel@jms.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
